<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\ScanFolderToFile.Core\ScanFolderToFile.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>ScanFolderToFile.App.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="../../scanFolderToFile/Resources/Deleket-Sleek-Xp-Basic-Files.ico" Link="Assets/Deleket-Sleek-Xp-Basic-Files.ico" />
    <AvaloniaXaml Update="**/*.axaml">
      <Generator>MSBuild:Compile</Generator>
    </AvaloniaXaml>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ScanFolderToFile.App</RootNamespace>
    <AssemblyName>ScanFolderToFile</AssemblyName>
    <UseAppHost>true</UseAppHost>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
</Project>
