<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ScanFolderToFile.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="QuestPDF" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>ScanFolderToFile.Core.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
